# Generated by Django 3.1.7 on 2021-03-12 14:56

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgroUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('number', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Viloyat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Yangilik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('malumoti_qisqacha', models.TextField()),
                ('toifa', models.SmallIntegerField(null=True)),
                ('name', models.CharField(max_length=100)),
                ('reklama_turi', models.SmallIntegerField(null=True)),
                ('biznes', models.BooleanField(default=True)),
                ('holat', models.SmallIntegerField()),
                ('chiqarilgan_yili', models.IntegerField()),
                ('summa_narxi', models.BigIntegerField()),
                ('pul_turi', models.SmallIntegerField()),
                ('kelishilgan', models.BooleanField(null=True)),
                ('rasmlar', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='images/'), blank=True, default=[], size=None)),
                ('viloyat_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agro_app.viloyat')),
            ],
        ),
        migrations.CreateModel(
            name='Tuman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('vil_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agro_app.viloyat')),
            ],
        ),
    ]
