# Generated by Django 3.1.7 on 2021-03-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agrouser',
            name='is_agree',
            field=models.BooleanField(null=True),
        ),
    ]
